service: testkdistrib

custom:
  stage: ${opt:stage, self:provider.stage} 
  lambdaRole: testkdistrib-${self:custom.stage}-lambdaRole
  region: ap-southeast-2


resources: ${file(./resources.yml)}

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  role: LambdaAll  
  versionLambda: false  
package:
  individually: true
  exclude:    
    - '**/*'
  include:      
    - node_modules/**
    - types/*.js
functions:  
  test-kc:    
    package:
      include:
        - index.js
    handler: index.handler    
    environment:
      LD_LIBRARY_PATH: './node_modules/node-rdkafka/build/deps'
  